### ISSUE TITLE
Search data mixes the order of experiments in README.yaml and that forces recalculation

### ISSUE THREAD

**Issue by comcon1** [NMRLipids/Databank#162]
I run `searchDATABANK.py` to calculate the comparison for newly added data. After that, git showed me a lot of modified README.yaml files. A new experiment was added for the comparison to some of them. However, in some files, the order of experiments was just mixed:

**before**
```
EXPERIMENT:
  ORDERPARAMETER:
    POPE:
      unpublished/ferreiraPOPE: unpublished/ferreiraPOPE/1
      10.1021/jacs.1c05549: 10.1021/jacs.1c05549/2
  FORMFACTOR: 10.1021/jp511159q/1
```
**after**
```
EXPERIMENT:
  ORDERPARAMETER:
    POPE:
      10.1021/jacs.1c05549: 10.1021/jacs.1c05549/2
      unpublished/ferreiraPOPE: unpublished/ferreiraPOPE/1
  FORMFACTOR: 10.1021/jp511159q/1
```

That mixes in turn the order inside OrderParameterQuality.json files and both files are set up as changed. It's bad behavior because in fact there is no change. A contributor can miss that fact and commit such change alongside another. 

So, I suppose, that the experiment order should be strictly determined.
