### ISSUE TITLE
AddData.py adds extra lines to README.yml causing errors

### ISSUE THREAD

**Issue by MagnusSletten** [NMRLipids/Databank#275]
**Describe the bug**
Running AddData.py on any info.yml file produces README.yml with an unintended line at the top for instance: 

```
 !!python/object:DatabankLib.core.System
_store:
  DOI: 10.5281/zenodo.11614468
  SOFTWARE: gromacs
  TRJ:
  - - 566.xtc
  TPR:
```
The first line should not be added. 

I suspect there is just a one line change needed in AddData.py. Maybe:

```
with open(outfile_dict, "w") as f:
yaml.dump(sim, f, sort_keys=False, allow_unicode=True)
```

should be:

```
 with open(outfile_dict, "w") as f:
 yaml.dump(sim.readme, f, sort_keys=False, allow_unicode=True)
```
